ALTER TABLE orders
ADD COLUMN IF NOT EXISTS driver_id TEXT,
ADD COLUMN IF NOT EXISTS delivery_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS no_driver_found_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS delivery_auto_retry_count INTEGER DEFAULT 0;
