// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxKJFkUTQbL-_1fs26vpUrNTcPjUhxnXQ',
    appId: '1:321519047207:web:22953647e76e42cb047402',
    messagingSenderId: '321519047207',
    projectId: 'ammarjo-1',
    authDomain: 'ammarjo-1.firebaseapp.com',
    storageBucket: 'ammarjo-1.firebasestorage.app',
    measurementId: 'G-3LTG3D46ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATt4I13n5lZRe5VLtw38wIx8EMMpYurVo',
    appId: '1:321519047207:android:1549fa3095147dfa047402',
    messagingSenderId: '321519047207',
    projectId: 'ammarjo-1',
    storageBucket: 'ammarjo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdvhqunvA5LN2w-HiuwXcc0LzfeyytCg',
    appId: '1:321519047207:ios:92fb5094f48caa07047402',
    messagingSenderId: '321519047207',
    projectId: 'ammarjo-1',
    storageBucket: 'ammarjo-1.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdvhqunvA5LN2w-HiuwXcc0LzfeyytCg',
    appId: '1:321519047207:ios:c0333b4c87237bb2047402',
    messagingSenderId: '321519047207',
    projectId: 'ammarjo-1',
    storageBucket: 'ammarjo-1.firebasestorage.app',
    iosBundleId: 'com.ammar.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxKJFkUTQbL-_1fs26vpUrNTcPjUhxnXQ',
    appId: '1:321519047207:web:4a0b0ed23660aa95047402',
    messagingSenderId: '321519047207',
    projectId: 'ammarjo-1',
    authDomain: 'ammarjo-1.firebaseapp.com',
    storageBucket: 'ammarjo-1.firebasestorage.app',
    measurementId: 'G-C9C63L0883',
  );
}
